package com.example.badnewgym.feature.memberintelligence.domain.model

data class MemberEvent(
    val id: String,
    val memberId: String,
    val gymId: String,
    val eventType: EventType,
    val occurredAt: Long,
    val source: EventSource = EventSource.SYSTEM,
    val actorId: String? = null,
    val metadata: Map<String, String> = emptyMap(),
    val createdAt: Long = occurredAt,
    val idempotencyKey: String? = null
)

enum class EventType {
    CHECK_IN,
    CHECK_OUT,
    PAYMENT,
    PAYMENT_FAILED,
    NEW_MEMBER,
    WALK_IN,
    RENEWAL,
    EXPIRED,
    FREEZE,
    REACTIVATION,
    TRAINER_SESSION,
    WORKOUT,
    SUPPLEMENT_PURCHASE,
    NUTRITION,
    SERVICE_PURCHASE,
    SERVICE_ACTIVATED,
    SERVICE_DEACTIVATED,
    SERVICE_BOOKED,
    SERVICE_USED,
    SERVICE_EXPIRED,
    SERVICE_ISSUE,
    COMPLAINT,
    COMPLAINT_RESOLVED,
    MAINTENANCE,
    MACHINE_FAULT,
    MACHINE_REPORTED,
    MACHINE_FIXED,
    MAINTENANCE_STARTED,
    MAINTENANCE_COMPLETED,
    CLEANING_STARTED,
    CLEANING_COMPLETED,
    STOCK_LOW,
    INCIDENT_REPORTED,
    INCIDENT_RESOLVED,
    ANNOUNCEMENT,
    OFFER,
    TRAINER_ASSIGNED,
    TRAINER_SESSION_SCHEDULED,
    TRAINER_SESSION_STARTED,
    TRAINER_SESSION_COMPLETED,
    TRAINER_SESSION_MISSED,
    TRAINER_SESSION_CANCELLED,
    WORKOUT_STARTED,
    WORKOUT_COMPLETED,
    WORKOUT_SKIPPED,
    PR_ACHIEVED,
    GOAL_UPDATED,
    BODY_MEASUREMENT_UPDATED,
    TRIAL_STARTED,
    TRIAL_CONVERTED,
    TRIAL_EXPIRED,
    FREEZE_STARTED,
    FREEZE_ENDED,
    BANNED,
    BAN_LIFTED,
    MEMBER_CREATED,
    MEMBER_UPDATED,
    MEMBERSHIP_STARTED,
    MEMBERSHIP_RENEWED,
    MEMBERSHIP_EXPIRED,
    MEMBERSHIP_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_DUE,
    PAYMENT_OVERDUE,
    PAYMENT_PARTIAL,
    REFUND,
    INVOICE_CREATED,
    PACKAGE_PURCHASED,
    UNKNOWN;

    fun displayLabel(): String = when (this) {
        CHECK_IN -> "CHECK-IN"
        CHECK_OUT -> "CHECK-OUT"
        PAYMENT -> "PAYMENT"
        PAYMENT_FAILED -> "PAYMENT FAILED"
        NEW_MEMBER -> "NEW MEMBER"
        WALK_IN -> "WALK-IN"
        RENEWAL -> "RENEWAL"
        EXPIRED -> "EXPIRED"
        FREEZE -> "FREEZE"
        REACTIVATION -> "REACTIVATION"
        TRAINER_SESSION -> "PT SESSION"
        WORKOUT -> "WORKOUT"
        SUPPLEMENT_PURCHASE -> "SUPPLEMENT"
        NUTRITION -> "NUTRITION"
        SERVICE_PURCHASE -> "SERVICE"
        SERVICE_ACTIVATED -> "SERVICE ACTIVE"
        SERVICE_DEACTIVATED -> "SERVICE INACTIVE"
        SERVICE_BOOKED -> "SERVICE BOOKED"
        SERVICE_USED -> "SERVICE USED"
        SERVICE_EXPIRED -> "SERVICE EXPIRED"
        SERVICE_ISSUE -> "SERVICE ISSUE"
        COMPLAINT -> "COMPLAINT"
        COMPLAINT_RESOLVED -> "COMPLAINT RESOLVED"
        MAINTENANCE -> "MAINTENANCE"
        MACHINE_FAULT -> "MACHINE FAULT"
        MACHINE_REPORTED -> "MACHINE REPORTED"
        MACHINE_FIXED -> "MACHINE FIXED"
        MAINTENANCE_STARTED -> "MAINTENANCE STARTED"
        MAINTENANCE_COMPLETED -> "MAINTENANCE COMPLETED"
        CLEANING_STARTED -> "CLEANING STARTED"
        CLEANING_COMPLETED -> "CLEANING COMPLETED"
        STOCK_LOW -> "STOCK LOW"
        INCIDENT_REPORTED -> "INCIDENT REPORTED"
        INCIDENT_RESOLVED -> "INCIDENT RESOLVED"
        ANNOUNCEMENT -> "ANNOUNCEMENT"
        OFFER -> "OFFER"
        TRAINER_ASSIGNED -> "TRAINER ASSIGNED"
        TRAINER_SESSION_SCHEDULED -> "PT SESSION SCHEDULED"
        TRAINER_SESSION_STARTED -> "PT SESSION STARTED"
        TRAINER_SESSION_COMPLETED -> "PT SESSION COMPLETED"
        TRAINER_SESSION_MISSED -> "PT SESSION MISSED"
        TRAINER_SESSION_CANCELLED -> "PT SESSION CANCELLED"
        WORKOUT_STARTED -> "WORKOUT STARTED"
        WORKOUT_COMPLETED -> "WORKOUT COMPLETED"
        WORKOUT_SKIPPED -> "WORKOUT SKIPPED"
        PR_ACHIEVED -> "PERSONAL RECORD"
        GOAL_UPDATED -> "GOAL UPDATED"
        BODY_MEASUREMENT_UPDATED -> "BODY MEASUREMENT"
        TRIAL_STARTED -> "TRIAL STARTED"
        TRIAL_CONVERTED -> "TRIAL CONVERTED"
        TRIAL_EXPIRED -> "TRIAL EXPIRED"
        FREEZE_STARTED -> "FREEZE STARTED"
        FREEZE_ENDED -> "FREEZE ENDED"
        BANNED -> "ACCESS BANNED"
        BAN_LIFTED -> "BAN LIFTED"
        MEMBER_CREATED -> "MEMBER CREATED"
        MEMBER_UPDATED -> "MEMBER UPDATED"
        MEMBERSHIP_STARTED -> "MEMBERSHIP STARTED"
        MEMBERSHIP_RENEWED -> "MEMBERSHIP RENEWED"
        MEMBERSHIP_EXPIRED -> "MEMBERSHIP EXPIRED"
        MEMBERSHIP_CANCELLED -> "MEMBERSHIP CANCELLED"
        PAYMENT_SUCCESS -> "PAYMENT SUCCESS"
        PAYMENT_DUE -> "PAYMENT DUE"
        PAYMENT_OVERDUE -> "PAYMENT OVERDUE"
        PAYMENT_PARTIAL -> "PAYMENT PARTIAL"
        REFUND -> "REFUND"
        INVOICE_CREATED -> "INVOICE CREATED"
        PACKAGE_PURCHASED -> "PACKAGE PURCHASED"
        UNKNOWN -> "EVENT"
    }
}
