package com.example.badnewgym.feature.memberintelligence.design.colors

import androidx.compose.ui.graphics.Color

data class BADGymColors(
    val background: Color,
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceMuted: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val textOnAccent: Color,
    val border: Color,
    val divider: Color,
    val accent: Color,
    val accentSoft: Color,
    val accentStrong: Color,
    val success: Color,
    val successSoft: Color,
    val warning: Color,
    val warningSoft: Color,
    val danger: Color,
    val dangerSoft: Color,
    val info: Color,
    val infoSoft: Color,
    val vip: Color,
    val vipSoft: Color,
    val railBackground: Color,
    val railActiveBackground: Color,
    val railActiveIcon: Color,
    val railInactiveIcon: Color,
    val ctaGradient: List<Color>,
    val cardGlow: Color,
    val brandAccent: Color,
    val mottoColor: Color
)

// 1. NATURAL FRESH (Ivory + Emerald/Mint + Botanical Vector)
val NaturalFreshColors = BADGymColors(
    background = Color(0xFFF4F9F5),
    surface = Color(0xFFFFFFFF),
    surfaceElevated = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFE8F5EC),
    textPrimary = Color(0xFF132A1C),
    textSecondary = Color(0xFF2D573B),
    textMuted = Color(0xFF5E826B),
    textOnAccent = Color(0xFFFFFFFF),
    border = Color(0xFFD3E8DA),
    divider = Color(0xFFE5F2EA),
    accent = Color(0xFF16A34A),
    accentSoft = Color(0xFFDCFCE7),
    accentStrong = Color(0xFF15803D),
    success = Color(0xFF16A34A),
    successSoft = Color(0xFFDCFCE7),
    warning = Color(0xFFD97706),
    warningSoft = Color(0xFFFEF3C7),
    danger = Color(0xFFDC2626),
    dangerSoft = Color(0xFFFEE2E2),
    info = Color(0xFF0284C7),
    infoSoft = Color(0xFFE0F2FE),
    vip = Color(0xFFD97706),
    vipSoft = Color(0xFFFEF3C7),
    railBackground = Color(0xFFEBF5EE),
    railActiveBackground = Color(0xFF16A34A),
    railActiveIcon = Color(0xFFFFFFFF),
    railInactiveIcon = Color(0xFF335C43),
    ctaGradient = listOf(Color(0xFF16A34A), Color(0xFF15803D)),
    cardGlow = Color(0x2216A34A),
    brandAccent = Color(0xFF16A34A),
    mottoColor = Color(0xFF2D6A4F)
)

// 2. CORAL PINK (Warm White + Coral/Pink)
val VibrantGradientColors = BADGymColors(
    background = Color(0xFFFFF5F6),
    surface = Color(0xFFFFFFFF),
    surfaceElevated = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFFFEBEF),
    textPrimary = Color(0xFF2C151A),
    textSecondary = Color(0xFF88293D),
    textMuted = Color(0xFFA65A6C),
    textOnAccent = Color(0xFFFFFFFF),
    border = Color(0xFFFED2D9),
    divider = Color(0xFFFFE4E8),
    accent = Color(0xFFE11D48),
    accentSoft = Color(0xFFFFE4E6),
    accentStrong = Color(0xFFBE123C),
    success = Color(0xFF16A34A),
    successSoft = Color(0xFFDCFCE7),
    warning = Color(0xFFD97706),
    warningSoft = Color(0xFFFEF3C7),
    danger = Color(0xFFDC2626),
    dangerSoft = Color(0xFFFEE2E2),
    info = Color(0xFF0284C7),
    infoSoft = Color(0xFFE0F2FE),
    vip = Color(0xFFD97706),
    vipSoft = Color(0xFFFEF3C7),
    railBackground = Color(0xFFFDF0F3),
    railActiveBackground = Color(0xFFE11D48),
    railActiveIcon = Color(0xFFFFFFFF),
    railInactiveIcon = Color(0xFF88293D),
    ctaGradient = listOf(Color(0xFFE11D48), Color(0xFFBE123C)),
    cardGlow = Color(0x22E11D48),
    brandAccent = Color(0xFFE11D48),
    mottoColor = Color(0xFF88293D)
)

// 3. GOLD LIGHT (Ivory + Champagne/Gold)
val Premium3DColors = BADGymColors(
    background = Color(0xFFFAF7F0),
    surface = Color(0xFFFFFFFF),
    surfaceElevated = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFF4EDE0),
    textPrimary = Color(0xFF2B2314),
    textSecondary = Color(0xFF7C5E10),
    textMuted = Color(0xFF9E8445),
    textOnAccent = Color(0xFFFFFFFF),
    border = Color(0xFFEDE0C8),
    divider = Color(0xFFF4EBD9),
    accent = Color(0xFFD97706),
    accentSoft = Color(0xFFFEF3C7),
    accentStrong = Color(0xFFB45309),
    success = Color(0xFF16A34A),
    successSoft = Color(0xFFDCFCE7),
    warning = Color(0xFFD97706),
    warningSoft = Color(0xFFFEF3C7),
    danger = Color(0xFFDC2626),
    dangerSoft = Color(0xFFFEE2E2),
    info = Color(0xFF0284C7),
    infoSoft = Color(0xFFE0F2FE),
    vip = Color(0xFFD97706),
    vipSoft = Color(0xFFFEF3C7),
    railBackground = Color(0xFFF5EFE3),
    railActiveBackground = Color(0xFFD97706),
    railActiveIcon = Color(0xFFFFFFFF),
    railInactiveIcon = Color(0xFF7C5E10),
    ctaGradient = listOf(Color(0xFFD97706), Color(0xFFB45309)),
    cardGlow = Color(0x22D97706),
    brandAccent = Color(0xFFD97706),
    mottoColor = Color(0xFF7C5E10)
)

// 4. MINT MINIMAL (Clean White + Fresh Mint)
val MinimalDarkColors = BADGymColors(
    background = Color(0xFFF3FAF7),
    surface = Color(0xFFFFFFFF),
    surfaceElevated = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFE2F4ED),
    textPrimary = Color(0xFF0F2922),
    textSecondary = Color(0xFF2A594D),
    textMuted = Color(0xFF5A857B),
    textOnAccent = Color(0xFFFFFFFF),
    border = Color(0xFFCEECE3),
    divider = Color(0xFFDFFAF0),
    accent = Color(0xFF0D9488),
    accentSoft = Color(0xFFCCFBF1),
    accentStrong = Color(0xFF0F766E),
    success = Color(0xFF16A34A),
    successSoft = Color(0xFFDCFCE7),
    warning = Color(0xFFD97706),
    warningSoft = Color(0xFFFEF3C7),
    danger = Color(0xFFDC2626),
    dangerSoft = Color(0xFFFEE2E2),
    info = Color(0xFF0284C7),
    infoSoft = Color(0xFFE0F2FE),
    vip = Color(0xFFD97706),
    vipSoft = Color(0xFFFEF3C7),
    railBackground = Color(0xFFE6F5EF),
    railActiveBackground = Color(0xFF0D9488),
    railActiveIcon = Color(0xFFFFFFFF),
    railInactiveIcon = Color(0xFF2A594D),
    ctaGradient = listOf(Color(0xFF0D9488), Color(0xFF0F766E)),
    cardGlow = Color(0x220D9488),
    brandAccent = Color(0xFF0D9488),
    mottoColor = Color(0xFF2A594D)
)

// 5. AQUA GLASS (Translucent White + Aqua/Sky)
val GlassmorphismColors = BADGymColors(
    background = Color(0xFFF0F9FF),
    surface = Color(0xFFFFFFFF),
    surfaceElevated = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFE0F2FE),
    textPrimary = Color(0xFF0C273D),
    textSecondary = Color(0xFF0369A1),
    textMuted = Color(0xFF4B7B9F),
    textOnAccent = Color(0xFFFFFFFF),
    border = Color(0xFFBAE6FD),
    divider = Color(0xFFE0F2FE),
    accent = Color(0xFF0284C7),
    accentSoft = Color(0xFFE0F2FE),
    accentStrong = Color(0xFF0369A1),
    success = Color(0xFF16A34A),
    successSoft = Color(0xFFDCFCE7),
    warning = Color(0xFFD97706),
    warningSoft = Color(0xFFFEF3C7),
    danger = Color(0xFFDC2626),
    dangerSoft = Color(0xFFFEE2E2),
    info = Color(0xFF0284C7),
    infoSoft = Color(0xFFE0F2FE),
    vip = Color(0xFFD97706),
    vipSoft = Color(0xFFFEF3C7),
    railBackground = Color(0xFFE0F2FE),
    railActiveBackground = Color(0xFF0284C7),
    railActiveIcon = Color(0xFFFFFFFF),
    railInactiveIcon = Color(0xFF0369A1),
    ctaGradient = listOf(Color(0xFF0284C7), Color(0xFF0369A1)),
    cardGlow = Color(0x220284C7),
    brandAccent = Color(0xFF0284C7),
    mottoColor = Color(0xFF0369A1)
)

// 6. SUNSET PEACH (Warm White + Peach/Coral)
val BeastModeColors = BADGymColors(
    background = Color(0xFFFFF7ED),
    surface = Color(0xFFFFFFFF),
    surfaceElevated = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFFFEDD5),
    textPrimary = Color(0xFF331B0B),
    textSecondary = Color(0xFF9A3412),
    textMuted = Color(0xFFB45309),
    textOnAccent = Color(0xFFFFFFFF),
    border = Color(0xFFFED7AA),
    divider = Color(0xFFFFEDD5),
    accent = Color(0xFFEA580C),
    accentSoft = Color(0xFFFFEDD5),
    accentStrong = Color(0xFFC2410C),
    success = Color(0xFF16A34A),
    successSoft = Color(0xFFDCFCE7),
    warning = Color(0xFFD97706),
    warningSoft = Color(0xFFFEF3C7),
    danger = Color(0xFFDC2626),
    dangerSoft = Color(0xFFFEE2E2),
    info = Color(0xFF0284C7),
    infoSoft = Color(0xFFE0F2FE),
    vip = Color(0xFFD97706),
    vipSoft = Color(0xFFFEF3C7),
    railBackground = Color(0xFFFDF0E2),
    railActiveBackground = Color(0xFFEA580C),
    railActiveIcon = Color(0xFFFFFFFF),
    railInactiveIcon = Color(0xFF9A3412),
    ctaGradient = listOf(Color(0xFFEA580C), Color(0xFFC2410C)),
    cardGlow = Color(0x22EA580C),
    brandAccent = Color(0xFFEA580C),
    mottoColor = Color(0xFF9A3412)
)

// 7. ROYAL PURPLE LIGHT (White + Soft Purple)
val PurpleRoyalColors = BADGymColors(
    background = Color(0xFFFAF5FF),
    surface = Color(0xFFFFFFFF),
    surfaceElevated = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFF3E8FF),
    textPrimary = Color(0xFF241438),
    textSecondary = Color(0xFF6B21A8),
    textMuted = Color(0xFF9333EA),
    textOnAccent = Color(0xFFFFFFFF),
    border = Color(0xFFE9D5FF),
    divider = Color(0xFFF3E8FF),
    accent = Color(0xFF7E22CE),
    accentSoft = Color(0xFFF3E8FF),
    accentStrong = Color(0xFF6B21A8),
    success = Color(0xFF16A34A),
    successSoft = Color(0xFFDCFCE7),
    warning = Color(0xFFD97706),
    warningSoft = Color(0xFFFEF3C7),
    danger = Color(0xFFDC2626),
    dangerSoft = Color(0xFFFEE2E2),
    info = Color(0xFF0284C7),
    infoSoft = Color(0xFFE0F2FE),
    vip = Color(0xFFD97706),
    vipSoft = Color(0xFFFEF3C7),
    railBackground = Color(0xFFF5ECFD),
    railActiveBackground = Color(0xFF7E22CE),
    railActiveIcon = Color(0xFFFFFFFF),
    railInactiveIcon = Color(0xFF6B21A8),
    ctaGradient = listOf(Color(0xFF7E22CE), Color(0xFF6B21A8)),
    cardGlow = Color(0x227E22CE),
    brandAccent = Color(0xFF7E22CE),
    mottoColor = Color(0xFF6B21A8)
)

// 8. PREMIUM IVORY (Ivory + Restrained Warm Metallic)
val FuturisticNeonColors = BADGymColors(
    background = Color(0xFFF9F6F0),
    surface = Color(0xFFFFFFFF),
    surfaceElevated = Color(0xFFFFFFFF),
    surfaceMuted = Color(0xFFEFE9DC),
    textPrimary = Color(0xFF2A261F),
    textSecondary = Color(0xFF685E4E),
    textMuted = Color(0xFF8C8272),
    textOnAccent = Color(0xFFFFFFFF),
    border = Color(0xFFE4DAC8),
    divider = Color(0xFFEFE9DC),
    accent = Color(0xFFB45309),
    accentSoft = Color(0xFFFEF3C7),
    accentStrong = Color(0xFF92400E),
    success = Color(0xFF16A34A),
    successSoft = Color(0xFFDCFCE7),
    warning = Color(0xFFD97706),
    warningSoft = Color(0xFFFEF3C7),
    danger = Color(0xFFDC2626),
    dangerSoft = Color(0xFFFEE2E2),
    info = Color(0xFF0284C7),
    infoSoft = Color(0xFFE0F2FE),
    vip = Color(0xFFD97706),
    vipSoft = Color(0xFFFEF3C7),
    railBackground = Color(0xFFF2ECE0),
    railActiveBackground = Color(0xFFB45309),
    railActiveIcon = Color(0xFFFFFFFF),
    railInactiveIcon = Color(0xFF685E4E),
    ctaGradient = listOf(Color(0xFFB45309), Color(0xFF92400E)),
    cardGlow = Color(0x22B45309),
    brandAccent = Color(0xFFB45309),
    mottoColor = Color(0xFF685E4E)
)
